
# get all the database of links list
GET http://localhost:3000/links


###
GET http://localhost:3000/links/?page=1&size=2

###
# send links and add them to the database
# POST http://localhost:3000/links
POST http://localhost:3000/links
Content-Type: application/json

{
    "title": "TEST GROTEZCO",
    "link": "https://bitcoin.org/"
}

###
# search in database between all links
GET http://localhost:3000/links/63403a5e0b07c18e32659c35


# delete link from database
###
DELETE  http://localhost:3000/links/6356b61a855d84888a53a5ae

### 

# edit title from link
PUT http://localhost:3000/links/63408e2516a9d19347478739
Content-Type: application/json

{
    "title": "This is the main page",
    "link": "https://p2pfoundation.ning.com/forum/topics/bitcoin-open-source?xg_source=activity"
}